"use client";
import { useState } from "react";

const infoRows = [["Size & Fit","Designed for a graceful, easy fit. The model is 5'6” and wears size S."],["Fabric & Care","Premium georgette with soft breathable lining. Dry clean only."],["Shipping & Returns","Ships within 2–3 business days. Easy returns and exchanges within 7 days."],["Customize Your Outfit","Need a different length or styling help? Our team can help you personalize your look."]];
const faqs = [["How do I choose my size?","Use the size selector above and check our Size Guide. If you are between sizes, we recommend choosing the larger size for a more comfortable fit."],["How should I care for this outfit?","We recommend dry cleaning only. Store folded in a cool, dry place and keep away from direct sunlight."],["How long will delivery take?","Orders are dispatched within 2–3 business days and typically arrive within 4–7 business days across India."],["Can I return or exchange my order?","Yes. We offer easy returns and exchanges within 7 days of delivery, provided the item is unworn and has its tags intact."]];

export default function ProductPage() {
  const [size,setSize]=useState("M"),[added,setAdded]=useState(false),[tab,setTab]=useState("Details"),[openInfo,setOpenInfo]=useState("Size & Fit"),[openFaq,setOpenFaq]=useState("");
  return <main><div className="shipping">✦ &nbsp; FREE SHIPPING ON ORDERS ABOVE ₹2999 &nbsp; ✦</div><header className="nav"><a className="logo" href="/">Carnival of Clothes <small>by nandini ♡</small></a><nav className="links"><a href="/shop">Collections</a><a href="/#story">Our Story</a><a href="/shop">Shop all</a></nav><div className="actions"><a className="icon-button" href="/">⌕</a><a className="icon-button">♡</a><a className="bag">♧<b>{added?1:0}</b></a></div></header><div className="breadcrumbs"><a href="/">Home</a><span>›</span><a href="/shop">Collections</a><span>›</span><span>Festive Wear</span><span>›</span><b>Rose Noor Anarkali Set</b></div>
  <section className="product-detail"><div className="detail-visual"><div className="detail-main"><img src="/product.jpg" alt="Rose Noor Anarkali Set"/></div><div className="detail-thumbs">{["10%","32%","54%","76%","90%"].map(p=><img src="/product.jpg" style={{objectPosition:`${p} center`}} alt="Product thumbnail" key={p}/>)}</div></div><div className="detail-copy"><span className="badge-label">BESTSELLER</span><span className="eyebrow">FESTIVE WEAR · CARNIVAL EDIT</span><h1>Rose Noor<br/><i>Anarkali Set</i></h1><p className="subcopy">Dusty Rose Hand Embroidered Anarkali with Dupatta</p><div className="price">₹6,499 <del>₹8,999</del> <small>28% OFF</small></div><p className="tax">Inclusive of all taxes</p><div className="rating">★★★★★ <span>4.8&nbsp; (126 reviews)</span></div><hr/><div className="select-head"><b>Select size</b><a>Size Guide</a></div><div className="sizes">{["XS","S","M","L","XL","XXL"].map(s=><button className={size===s?"chosen":""} onClick={()=>setSize(s)} key={s}>{s}</button>)}</div><p className="fit-note">ⓘ Model is 5'6” tall and is wearing size S</p><button className="detail-add" onClick={()=>setAdded(true)}>{added?"Added to bag ✓":"Add to bag"}</button><button className="detail-buy">Buy now</button><div className="info-accordions">{infoRows.map(([title,text])=><div className={openInfo===title?"info-row open":"info-row"} key={title}><button onClick={()=>setOpenInfo(openInfo===title?"":title)}><span>{title}</span><b>⌄</b></button>{openInfo===title&&<p>{text}</p>}</div>)}</div><div className="mini-perks"><span>♢<small>Premium quality</small></span><span>♧<small>Easy returns</small></span><span>♙<small>Secure payments</small></span><span>◎<small>Worldwide shipping</small></span></div></div></section>
  <section className="product-tabs"><div className="tab-buttons">{["Details","Size & Fit","Fabric & Care"].map(t=><button className={tab===t?"on":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="tab-content">{tab==="Details"&&<><p>A timeless dusty rose Anarkali set crafted in premium georgette with intricate hand embroidery. Paired with a matching dupatta featuring delicate sequin work. Perfect for weddings, festive celebrations and special occasions.</p><ul><li>Anarkali with full flair</li><li>Hand embroidery with zari, thread & sequin work</li><li>Comes with embroidered dupatta</li><li>Comfortable breathable lining</li><li>Ideal for festive & wedding wear</li></ul></>}{tab==="Size & Fit"&&<p>Designed for a graceful, easy fit. The model is 5'6” and wears size S. Choose your usual size or refer to our size guide for measurements.</p>}{tab==="Fabric & Care"&&<p>Premium georgette with soft breathable lining. Dry clean only. Store folded in a cool, dry place and keep away from direct sunlight.</p>}</div></section>
  <section className="reviews"><div className="reviews-head"><div><span className="eyebrow">CUSTOMER LOVE</span><h2>Reviews <i>(126)</i></h2></div><a>View all&nbsp; →</a></div><div className="review-summary"><div className="score">4.8<strong>★★★★★</strong><small>(126 reviews)</small></div><div className="bars">{[["5","92%"],["4","6%"],["3","2%"],["2","0%"],["1","0%"]].map(([star,percent])=><div key={star}><span>{star} ★</span><i><b style={{width:percent}}/></i><em>{percent}</em></div>)}</div></div><div className="review-card"><div className="review-avatar">PS</div><div><b>Priya Sharma</b><span>Verified Buyer</span><small>12 May 2024</small><div className="review-stars">★★★★★</div><p>The quality is absolutely stunning! The embroidery, fit and color — everything is just perfect. Got so many compliments!</p></div><img src="/product.jpg" alt="Customer wearing Rose Noor Anarkali Set"/></div></section>
  <section className="faq"><div className="faq-heading"><span className="eyebrow">NEED TO KNOW</span><h2>Frequently asked <i>questions</i></h2><p>Everything you need to know before your piece finds a place in your wardrobe.</p></div><div className="faq-list">{faqs.map(([q,a])=><div className={openFaq===q?"faq-item open":"faq-item"} key={q}><button onClick={()=>setOpenFaq(openFaq===q?"":q)}><span>{q}</span><b>{openFaq===q?"−":"+"}</b></button>{openFaq===q&&<p>{a}</p>}</div>)}</div></section><section className="love"><span>♡</span><div><span className="eyebrow">WHY YOU’LL LOVE IT</span><h2>Made for <i>your moments.</i></h2></div><p>Elegant design · Premium fabrics · Intricate embroidery · Perfect for occasions</p></section></main>;
}
