"use client";

import { FormEvent, useState } from "react";
import { showGlobalStatus } from "@/app/global-status";

export type AdminSettings = { announcementEnabled: boolean; announcementMessage: string; announcementLink: string; freeShippingThreshold: number; shippingCharge: number; codEnabled: boolean; maintenanceMode: boolean; razorpayEnabled: boolean };

export default function AdminSettingsForm({ initial }: { initial: AdminSettings }) {
  const [busy,setBusy]=useState(false);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({announcementEnabled:form.get("announcementEnabled")==="on",announcementMessage:form.get("announcementMessage"),announcementLink:form.get("announcementLink"),freeShippingThreshold:Number(form.get("freeShippingThreshold")),shippingCharge:Number(form.get("shippingCharge")),codEnabled:form.get("codEnabled")==="on",maintenanceMode:form.get("maintenanceMode")==="on"})});const payload=await response.json();setBusy(false);showGlobalStatus(response.ok?"Store settings saved":payload.error||"Unable to save",response.ok?"success":"error")};
  return <form className="admin-form" onSubmit={submit}><div className="admin-panel" style={{padding:20,margin:0}}><h2>Announcement</h2><div className="admin-form-grid" style={{marginTop:18}}><div className="admin-field full"><label>Message</label><input name="announcementMessage" maxLength={160} defaultValue={initial.announcementMessage}/></div><div className="admin-field full"><label>Optional link</label><input name="announcementLink" defaultValue={initial.announcementLink} placeholder="/shop"/></div></div><div className="admin-checks" style={{marginTop:15}}><label><input name="announcementEnabled" type="checkbox" defaultChecked={initial.announcementEnabled}/> Show announcement</label></div></div><div className="admin-panel" style={{padding:20,margin:0}}><h2>Checkout and delivery</h2><div className="admin-form-grid" style={{marginTop:18}}><div className="admin-field"><label>Free shipping threshold</label><input name="freeShippingThreshold" type="number" min="0" defaultValue={initial.freeShippingThreshold}/></div><div className="admin-field"><label>Shipping charge</label><input name="shippingCharge" type="number" min="0" defaultValue={initial.shippingCharge}/></div></div><div className="admin-checks" style={{marginTop:15}}><label><input name="codEnabled" type="checkbox" defaultChecked={initial.codEnabled}/> Cash on delivery</label><label><input name="maintenanceMode" type="checkbox" defaultChecked={initial.maintenanceMode}/> Maintenance mode</label><label><input type="checkbox" checked={initial.razorpayEnabled} readOnly disabled/> Razorpay</label></div></div><button className="admin-button" disabled={busy}>{busy?"Saving…":"Save settings"}</button></form>;
}
